export const listaColores = [
	{ color: 'var(--color-Negro);', nombreColor: 'Negro', colorBooleano: false, id: 0 },
	{ color: 'var(--color-Blanco);', nombreColor: 'Blanco', colorBooleano: true, id: 1 },
	{ color: 'var(--color-AmarilloPollito);', nombreColor: 'Amarillo Pollito', colorBooleano: true, id: 2 },
	{ color: 'var(--color-Amarillo);', nombreColor: 'Amarillo', colorBooleano: true, id: 3 },
	{ color: 'var(--color-Dorado);', nombreColor: 'Dorado', colorBooleano: false, id: 4 }, 
	{ color: 'var(--color-Naranja);', nombreColor: 'Naranja', colorBooleano: false, id: 5 }, 
	{ color: 'var(--color-Mamey); ',nombreColor: 'Mamey', colorBooleano: false, id: 6 },
	{ color: 'var(--color-Rojo);', nombreColor: 'Rojo', colorBooleano: false, id: 7 },
	{ color: 'var(--color-RosadoChicle);', nombreColor: 'Rosado Chicle', colorBooleano: false, id: 8 },
	{ color: 'var(--color-RosadoFUcsia);', nombreColor: 'Rosado Fucsia', colorBooleano: false, id: 9 }, 
	{ color: 'var(--color-Rosado);', nombreColor: 'Rosado', colorBooleano: true, id: 10 },
	{ color: 'var(--color-RosadoViejo);', nombreColor: 'Rosado Viejo', colorBooleano: true, id: 11 },
	{ color: 'var(--color-MoradoLila);', nombreColor: 'Morado Lila', colorBooleano: true, id: 12 },
	{ color: 'var(--color-Morado);', nombreColor: 'Morado', colorBooleano: false, id: 13 },
	{ color: 'var(--color-AzulLapicero);', nombreColor: 'Azúl Lapicero', colorBooleano: false, id: 14 },
	{ color: 'var(--color-AzulEscolar);', nombreColor: 'Azúl Escolar', colorBooleano: true, id: 15 },
	{ color: 'var(--color-AzulTurqueza);', nombreColor: 'Azúl Turqueza', colorBooleano: false, id: 16 },
	{ color: 'var(--color-VerdeCotorra);', nombreColor: 'Verde Cotorra', colorBooleano: false, id: 17 },
	{ color: 'var(--color-VerdeLuminico);', nombreColor: 'Verde Lumínico', colorBooleano: true, id: 18 },
	{ color: 'var(--color-VerdeManzana);', nombreColor: 'Verde Manzana', colorBooleano: true, id: 19 },
	{ color: 'var(--color-Gris);', nombreColor: 'Gris', colorBooleano: true, id: 20 },
	{ color: 'var(--color-Marron);', nombreColor: 'Marrón', colorBooleano: false, id: 21 },
];